Repository Bitbox-Connect/Bitbox, pull requests merged in 2024-10, with the labels that each got.

#23 Create Code_of_Conduct.md
  Code_of_Conduct.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#26 Login/Signup page ui improved
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/component/css/Login.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#41 Readme.md for clear instruction how to run application
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#40 Email verification done
  client/src/App.jsx
  client/src/component/Verify.jsx
  client/src/component/forgotpass.jsx
  client/src/index.css
  server/.env.sample
  server/.gitignore
  server/Controllers/auth.js
  server/Controllers/profiles.js
  server/Models/User.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/profile.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#47 Bitbox Readme Over Content problem
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#56 Successfully added Github bot to respond Issues and PR
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#67 added placeholder in community page
  client/package-lock.json
  client/package.json
  client/src/component/Community.jsx
  client/src/component/Navbar.jsx
  server/.env.sample
  server/Controllers/projects.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#68 added input validations
  client/package-lock.json
  client/package.json
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/component/css/Login.css
  client/src/validations/validation.js
  server/package-lock.json
  server/package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#70 Create auto-comment-on-close.yml
  .github/workflows/auto-comment-on-close.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#73 Create auto-comment-pr-merge.yml
  .github/workflows/auto-comment-pr-merge.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#74 added email reset functionality
  client/src/component/Login.jsx
  server/Controllers/auth.js
  server/index.js
  server/routes/auth.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#75 Add 404 Page Component
  client/src/App.jsx
  client/src/component/NotFound.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#89 Added share feature
  client/package-lock.json
  client/package.json
  client/src/component/Home.jsx
  client/src/component/Share.jsx
  client/src/component/share.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#88 Upgraded the feedback form and its UI
  client/src/component/Footers/Feedback.jsx
  client/src/component/css/Feedback.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#87 custom cursor added
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/index.css
  client/src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#90 responsive #76
  client/package-lock.json
  client/src/App.jsx
  client/src/component/Navbar.jsx
  client/src/component/css/Navbar.css
  client/src/component/css/Theme.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#101 Dark mode & hover css effect not applied to a section and #96
  client/package-lock.json
  client/src/App.jsx
  client/src/component/Home.jsx
  client/src/component/HomePage/Card.jsx
  client/src/component/css/Card.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#100 Added missing import in header
  client/src/App.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#102 Style of what we work on changed and corrected
  client/src/App.jsx
  client/src/component/Home.jsx
  client/src/component/css/Home.css
  server/db.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#103 Fixed dark mode and light mode theme issues in footer, About Us segment, InputModal, Navbar and Login/Signup components; added PropTypes validation in About Us page and Discussions to prevent bugs, footer.
  client/package-lock.json
  client/src/component/About.jsx
  client/src/component/Discussion.jsx
  client/src/component/Firebase/Setup.js
  client/src/component/Footer.jsx
  client/src/component/Home.jsx
  client/src/component/InputModal.jsx
  client/src/component/Login.jsx
  client/src/component/Share.jsx
  client/src/component/Signup.jsx
  client/src/component/Verify.jsx
  client/src/component/css/Footer.css
  client/src/component/css/Login.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#112 Needed to change some code related to features
  server/Models/Profile.js
  server/routes/projects.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#128 added rate limiter to the login api issue #111
  server/package-lock.json
  server/package.json
  server/routes/auth.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#118 added env_sample file
  server/.env_sample
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#119 Css input error #98
  client/package-lock.json
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/component/css/Login.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#120 BUG: Notification Added during login and signup
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#125 Fixed the login and signup route
  client/src/App.jsx
  client/src/component/Discussion.jsx
  client/src/component/Login.jsx
  server/Controllers/auth.js
  server/Controllers/profiles.js
  server/db.js
  server/index.js
  server/routes/auth.js
  server/routes/projects.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#131 Ui fixed
  client/package-lock.json
  client/src/component/Home.css
  client/src/component/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#132 Improve the UI of the navbar.
  client/src/component/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#133 ProgressBar Added | Issue #114
  client/src/App.jsx
  client/src/component/ProgressBar/ProgressBar.css
  client/src/component/ProgressBar/ProgressBar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#141 fixed login page
  client/src/component/Login.jsx
  server/.env_sample
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#142 Added Smoothness in B2T, Enhancement Mode Toggling Buttons, Added Styling to Cards | Issue #134
  client/src/component/HomePage/Card.jsx
  client/src/component/Navbar.jsx
  client/src/component/ScrollTop.jsx
  client/src/component/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#143 #136 -- Enhancing UI .
  client/src/component/About.jsx
  client/src/component/css/About.css
  client/src/component/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#144 React Toast, and Form Validation Addition | Issue #135
  client/src/component/Footers/Contactus.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#149 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#163 Added Custome Scrolbar | Issue #145
  client/src/component/Navbar.jsx
  client/src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#164 Fix Navbar | Issue #140
  client/src/component/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#165 Added Custom Error Page
  client/src/App.jsx
  client/src/component/NotFound.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#161 Resolve the design issues of login & signup page
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/component/css/Login.css
  client/src/component/css/Signup.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#170 BUG: Improving the alignment
  client/src/component/Discussion.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#176 Improve the styling of FAQ section
  client/src/component/css/About.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#181 make word section responsive
  client/src/component/Home.css
  client/src/component/Home.jsx
  server/package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#179 Added scroll animations to hero and bitbox community section.
  client/src/component/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#182 Fix: Persistent Dark Mode Across Page Refreshes #174
  README.md
  client/src/App.jsx
  server/.env.sample
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#172 I have done changes in footer section to improve its appearance.
  client/src/component/css/Footer.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#193 Added table of contents to the readme file
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#183 Fix: Responsiveness Issue on Different Screen Sizes
  client/src/component/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#203 Create LICENSE
  LICENSE
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#204 Building up a Contact Channel in Readme.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#205 Integrate Password Recovery Feature #189
  client/package-lock.json
  client/src/App.jsx
  client/src/component/ForgotPassword.jsx
  client/src/component/Login.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#208 Github actions for more connectivity!
  .github/workflows/auto-comment-on-close.yml
  .github/workflows/auto-comment-pr-merge.yml
  .github/workflows/greetings.yml
  .github/workflows/issue_open_close.yml
  .github/workflows/pr-checker.yml
  .github/workflows/pr_merge.yaml
  .github/workflows/pr_raise.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#209 added multilanguage support for enhanced user experience #151
  client/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#225 Fixed glitching issues
  client/src/App.jsx
  client/src/component/Discussion.jsx
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/component/css/Login.css
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#217 login button working
  client/src/component/Login.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#238 Issue #202 -Ensure Protection to all the routes of the website such about us and discussion
  client/src/App.jsx
  client/src/component/Login.jsx
  client/src/component/ProtectedRoute.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#243 Add Helmet Middleware for Enhanced Security in the Backend
  server/index.js
  server/package-lock.json
  server/package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#246 Revamp Chatbox | ADD Appealing and Interactive user Features
  client/src/component/Discussion.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#247 Add blog page to the website
  client/src/App.jsx
  client/src/assets/blogs/1.webp
  client/src/assets/blogs/2.jpeg
  client/src/assets/blogs/3.png
  client/src/assets/blogs/4.jpeg
  client/src/assets/blogs/5.jpeg
  client/src/assets/blogs/6.png
  client/src/component/Blog.jsx
  client/src/component/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#244 ✨Add Visitor Counter feature done ! #211
  client/index.html
  client/visi.css
  client/visi.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#248 fix the responsive ness of the navbar and login page
  client/src/component/Login.jsx
  client/src/component/Navbar.jsx
  client/src/css/Login.css
  client/src/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#250 responsive edit profile page
  client/package-lock.json
  client/src/component/EditProfile.jsx
  client/src/component/Login.jsx
  client/src/css/EditProfile.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#251 Subscribe to newsletter frontend backend done : #245 done
  client/src/component/Footer.jsx
  server/.env.sample
  server/Controllers/OtherController.js
  server/Models/Newsletter.js
  server/routes/profile.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#254 Added AI supported chatbot
  client/src/App.jsx
  client/src/component/Footer.jsx
  client/src/css/ScrollTop.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#257 feat: Discussion page chat toggle, PR #233 (merge conflict solved) #234
  client/src/assets/images/Discussion/chat-pattern-dark.png
  client/src/component/Discussion.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#252 Added login to google funcanality
  client/package-lock.json
  client/package.json
  client/src/component/Firebase/Setup.js
  client/src/component/Login.jsx
  client/src/component/Navbar.jsx
  client/src/component/Signup.jsx
  client/src/contexts/authContext/index.jsx
  client/src/firebase/auth.js
  client/src/firebase/firebase.js
  client/src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#261 Added animation through out the website
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/About.jsx
  client/src/component/Footer.jsx
  client/src/component/Home.jsx
  client/src/component/HomePage/Card.jsx
  client/src/component/Login.jsx
  client/src/component/Testimonial.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#264 visitors and github stars button added : #253 done
  client/index.html
  client/src/component/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#266 Add a new contributors page done ! #213
  client/index.html
  client/src/component/Footer.jsx
  client/src/contributor.css
  client/src/contributor.html
  client/src/contributor.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#263 Added Stargazers and Forkers Profiles to README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#271 Refactor Navbar component and CSS
  client/src/component/Navbar.jsx
  client/src/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#272 improved feedback form
  client/src/component/Footers/Feedback.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#269 Updated the readme file
  README.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.png
  assets/image
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#275 Fix: UI Changes Needed for Translate Button and Language Display Issues
  client/visi.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#276 Added our contributor page with animation
  client/src/App.jsx
  client/src/component/Contributers.jsx
  client/src/component/Contributors.jsx
  client/src/component/Footer.jsx
  client/src/contributor.css
  client/src/contributor.html
  client/src/contributor.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#278 Remove Alert on Theme Change
  client/src/App.jsx
  client/src/component/Login.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#277 fixing scroll to top button
  client/src/component/ScrollTop.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#281 Add License Section to README.md✨
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#258 Added backend api of contact form
  client/src/component/Footers/Contactus.jsx
  server/Controllers/contact.js
  server/Models/Contact.js
  server/index.js
  server/routes/contact.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#285 Feedback form getting submitted successfully on database
  client/src/component/Footers/Feedback.jsx
  server/Controllers/Feedback.js
  server/Models/feedback.js
  server/index.js
  server/routes/feedback.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#286 New Feature: Added FAQ Section for Improved User Support
  client/src/App.jsx
  client/src/component/FAQ.css
  client/src/component/FAQ.jsx
  client/src/component/Footer.jsx
  client/src/component/Footers/FAQ.jsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#294 enhanced terms page
  client/src/component/Footers/TermOfUse.jsx
  client/src/css/Main.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#295 added cursor animation
  client/src/App.jsx
  client/src/component/Cursor.jsx
  client/src/css/Cursor.css
  client/src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#296 Add AI and Automation Enhancements
  client/package-lock.json
  client/src/App.jsx
  client/src/component/Ai.jsx
  client/src/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#300 Add Collaboration Features
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/Collab.jsx
  server/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#301 enhanced faq page
  client/src/App.jsx
  client/src/component/Faq.jsx
  client/src/component/Footer.jsx
  client/src/css/Faq.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#305 enhanced about us page
  client/src/component/About.jsx
  client/src/css/About.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#306 Add a pop up dialog box for subscribing to newsletter done ! #265
  client/index.html
  client/popup.jpg
  client/popup.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#304 Fix/navbar on mobile
  client/src/component/Footer.jsx
  client/src/component/Navbar.jsx
  client/src/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#308 Enhance/code of conduct
  client/src/component/Footers/Codeofconduct.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#314 Enhanced the ui of cards in home page
  client/src/component/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#315 fixed the bug in the footer
  client/src/component/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#317 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#318 Added fully functional blog page with backend
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/Blog.jsx
  client/src/component/CreateBlog.css
  client/src/component/CreateBlog.jsx
  server/Controllers/blogController.js
  server/Models/blog.js
  server/index.js
  server/routes/blog.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#320 Added animated faq section with both dark and light mode
  client/src/component/FAQ.css
  client/src/component/Faq.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest
