Repository Bitbox-Connect/Bitbox, pull requests merged in 2024-11, with the labels that each got.

#330 fixed profile update error
  client/src/component/Blog.jsx
  client/src/component/EditProfile.jsx
  client/src/css/EditProfile.css
  client/visi.js
  server/Controllers/profiles.js
  server/Models/Profile.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#337 Forgot password mail check exist or not #329 done
  client/src/component/ForgotPassword.jsx
  server/Controllers/auth.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#332 enhanced privacy page
  client/src/component/Footers/Privacypolicy.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#331 fixed input text
  client/src/component/Blog.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#309 Enhance/privacy policy
  client/src/component/Footers/Privacypolicy.jsx
  client/src/css/Main.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#343 Added send mail feature to contact us form for instant reply to user …
  server/Controllers/contact.js
  server/sendMail.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#351 Enhance Mongoose Schemas: Improved Validation and Security
  server/Models/Avatar.js
  server/Models/Contact.js
  server/Models/Newsletter.js
  server/Models/Profile.js
  server/Models/Project.js
  server/Models/User.js
  server/Models/blog.js
  server/Models/feedback.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#334 Added backend and frontend for read more page of blog
  client/src/App.jsx
  client/src/component/Blog.jsx
  client/src/component/ReadMoreBlog.jsx
  server/Controllers/blogController.js
  server/routes/blog.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#361 navbar fixed in both mode : #328 done
  client/src/component/Faq.jsx
  client/src/component/Navbar.jsx
  client/src/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#364 remember me" added to the signup and signin page connecting it to the local storage database for user authentication.
  client/src/component/Login.jsx
  client/src/component/Signup.jsx
  client/src/css/Login.css
  client/src/css/Signup.css
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#347 enchanced the UI of blog page to look for beautiful
  client/src/component/Blog.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#365 Fixed Contact us Alignment
  client/src/component/Footers/Contactus.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#375 Fixed Navbar Responsiveness for desktop and mobile
  client/src/component/Navbar.jsx
  client/src/css/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#372 Fixed homepage visitor counter to track unique visits only once per user session
  client/src/component/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#367 Fix Newsletter Popup Reappearance After User Dismissal
  client/popup.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#381 Fixed Home Page alignment with respect to navbar
  client/src/component/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#383 Added text to speak button on blog
  client/src/component/Blog.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#384 Share you blog on social media
  client/src/component/Blog.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#385 faq visible in dark mode
  client/src/App.jsx
  client/src/component/About.jsx
  client/src/component/Faq.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#388 Implemented CURD backend Api for total visitor count
  client/src/component/Footer.jsx
  client/src/component/Footers/VisitorCount.jsx
  server/Controllers/visitorController.js
  server/Models/Visitor.js
  server/index.js
  server/routes/visitor.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#392 Add Validation to contact us Message Field
  client/src/component/Footers/Contactus.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#395 Fix "About US" Page Hidden Behind Navbar
  client/src/component/About.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#402 Added mail functionality to feedback form
  client/src/component/Footers/Feedback.jsx
  server/.env.sample
  server/Controllers/Feedback.js
  server/sendFeedbackToAdmin.js
  server/sendMail.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#407 Implemented frontend and backend Project Showcase with Repository Integration
  client/src/App.jsx
  client/src/component/Navbar.jsx
  client/src/component/Projects.jsx
  client/src/component/UploadProject.jsx
  server/Controllers/projectController.js
  server/Models/ProjectSchema.js
  server/index.js
  server/routes/projects.js
  server/routes/projectsRoute.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#412 Improved Password Checklist UI and Fix "Remember Me" Functionality
  client/src/component/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#413 STYLING IMPROVED
  client/index.html
  client/src/component/Footer.jsx
  client/src/component/Footers/VisitorCount.jsx
  client/src/css/Footer.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#387 added news letter api
  server/Controllers/OtherController.js
  server/Controllers/assests/bitboximage.png
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#403 Refresh Render Issue Solved
  client/src/App.jsx
  client/src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#414 Added Project Structure.md
  Project Structure.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#401 Added subscribe us feature on newsletter
  client/src/App.jsx
  client/src/component/Footer.jsx
  server/Controllers/OtherController.js
  server/Models/Newsletter.js
  server/sendSubscribeMail.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#415 Uploadproject UI changes
  client/package-lock.json
  client/src/component/AddProject.jsx
  client/src/component/Faq.jsx
  client/src/component/Navbar.jsx
  client/src/component/UploadProject.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#421 enhances the styling of full blog page for both light and dark theme
  client/src/component/Blog.jsx
  client/src/component/Contributors.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#432 Interactive Discussion Forum with Responsive Design ✨
  client/package-lock.json
  client/src/App.jsx
  client/src/component/DiscussionForum.jsx
  client/src/component/faq.jsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#434 Efficiently add github and youtube link
  client/src/component/AddProject.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#437 Implemented otp based login functionality
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/Login.jsx
  client/src/component/LoginPhone.jsx
  client/src/component/Navbar.jsx
  client/src/contexts/authContext/index.jsx
  client/src/firebase/auth.js
  server/.env.sample
  server/Controllers/auth.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#438 [Bug]: the cursor animation is bugged #368
  client/src/component/Cursor.jsx
  client/src/css/Cursor.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#436 Admin login component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/Admin.jsx
  client/src/component/Dashboard.jsx
  server/Controllers/adminController.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#439 Dark mode Signup Bug
  client/src/App.jsx
  client/src/component/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#427 Added faq page
  client/package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest
